### ISSUE TITLE
Sometimes getting the track times out

### ISSUE THREAD

**Issue by palfrey** [palfrey/mopidy-tachikoma#4]
e.g.

```
Jul 15 00:09:19 mopidy-jukebox mopidy[7311]: Unhandled exception in thread started by <bound method TachikomaFrontend.doSlack of <mopidy_tachikoma.bot.TachikomaFrontend object at 0x73002710>>
Jul 15 00:09:19 mopidy-jukebox mopidy[7311]: Traceback (most recent call last):
Jul 15 00:09:19 mopidy-jukebox mopidy[7311]: File "/usr/local/lib/python2.7/dist-packages/mopidy_tachikoma/bot.py", line 33, in doSlack
Jul 15 00:09:19 mopidy-jukebox mopidy[7311]: current_track = self.core.playback.get_current_track().get(3)
Jul 15 00:09:19 mopidy-jukebox mopidy[7311]: File "/usr/local/lib/python2.7/dist-packages/pykka/threading.py", line 56, in get
Jul 15 00:09:19 mopidy-jukebox mopidy[7311]: raise Timeout('%s seconds' % timeout)
```

**Comment by palfrey** [comment]
Fixed by afc592cd6392614c77e1e30ef352c69235e3aa88
