### ISSUE TITLE
Cope better with failure to login to Slack

### ISSUE THREAD

**Issue by palfrey** [palfrey/mopidy-tachikoma#8]
```
Sep 14 05:24:33 mopidy-jukebox mopidy[6393]: INFO     Exception from Slack: error(32, 'Broken pipe')
Sep 14 05:25:56 mopidy-jukebox mopidy[6393]: Unhandled exception in thread started by <bound method TachikomaFrontend.doSlack of <mopidy_tachikoma.bot.TachikomaFrontend object at 0x71e4a350>>
Sep 14 05:25:57 mopidy-jukebox mopidy[6393]: Traceback (most recent call last):
Sep 14 05:25:58 mopidy-jukebox mopidy[6393]: File "/usr/local/lib/python2.7/dist-packages/mopidy_tachikoma/bot.py", line 57, in doSlack
Sep 14 05:26:00 mopidy-jukebox mopidy[6393]: last_track_told = self.doSlackRead(last_track_told)
Sep 14 05:26:01 mopidy-jukebox mopidy[6393]: File "/usr/local/lib/python2.7/dist-packages/mopidy_tachikoma/bot.py", line 35, in doSlackRead
Sep 14 05:26:01 mopidy-jukebox mopidy[6393]: self.new_slack_client()
Sep 14 05:26:01 mopidy-jukebox mopidy[6393]: File "/usr/local/lib/python2.7/dist-packages/mopidy_tachikoma/bot.py", line 18, in new_slack_client
Sep 14 05:26:01 mopidy-jukebox mopidy[6393]: raise Exception("Bad Slack token?")
Sep 14 05:26:03 mopidy-jukebox mopidy[6393]: Exception: Bad Slack token?
```

**Comment by palfrey** [comment]
We probably need https://github.com/slackhq/python-slackclient/pull/50 for better Slack exception info before this can be fixed
